# Generated by Django 3.0 on 2019-12-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='userSend',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(db_index=True, max_length=32)),
                ('time', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
