# Generated by Django 3.0 on 2019-12-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=128, null=True)),
                ('url', models.CharField(max_length=128, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('nt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tn', to='app01.newType')),
                ('userSend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='su', to='app01.userInfo')),
            ],
        ),
        migrations.CreateModel(
            name='favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userInfo')),
            ],
        ),
        migrations.CreateModel(
            name='commont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=164)),
                ('device', models.CharField(max_length=32, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userInfo')),
            ],
        ),
    ]
