# Generated by Django 3.0 on 2019-12-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191228_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='nt',
            field=models.IntegerField(choices=[(1, '42区'), (2, '段子'), (3, '图片'), (4, '挨踢1024'), (5, '你问我答')]),
        ),
        migrations.DeleteModel(
            name='newType',
        ),
    ]
