# Generated by Django 3.0 on 2019-12-28 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20191228_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='app01.comment'),
        ),
        migrations.DeleteModel(
            name='favor',
        ),
    ]
