# Generated by Django 3.0 on 2020-03-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20191228_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
