# Generated by Django 3.0 on 2020-03-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_news_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='zan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('bools', models.BooleanField(default=False, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.news')),
            ],
        ),
    ]
