# Generated by Django 3.0 on 2020-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200318_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='path',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
