# Generated by Django 3.0 on 2020-03-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20200320_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parentcomment',
        ),
    ]
