# Generated by Django 3.0 on 2020-03-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_comment_parentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='app01.comment'),
        ),
    ]
