# Generated by Django 3.0 on 2020-03-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20200323_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id'], 'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': '动态表', 'verbose_name_plural': '动态表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['nid'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
